spring.application.name=webar-restaurant

server.port=${PORT:8080}

# =========================================================
# ACTIVE PROFILE
# =========================================================
# Local  -> local
# Render -> prod
#
# Local default is "local"
# On Render, set SPRING_PROFILES_ACTIVE=prod
# =========================================================

spring.profiles.active=${SPRING_PROFILES_ACTIVE:local}


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false


# =========================================================
# FILE UPLOAD
# =========================================================

spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=500MB


# =========================================================
# CORS
# =========================================================

app.frontend-url=${FRONTEND_URL:https://webarqr.netlify.app}